name: cron-health-check
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check service health
        run: curl https://www.triviastack.com/api/health
